### PR TITLE
adding png with nested workflow 

### LINKED ISSUE #11: It appears the `nested_workflow.png` image in `1_intro_pydra.ipynb` is still missing. Couldn't find it in `figures/`..
It appears the `nested_workflow.png` image in `1_intro_pydra.ipynb` is still missing. Couldn't find it in `figures/`..

image

_Originally posted by @SamGuay in https://github.com/nipype/pydra-tutorial/issues/3#issuecomment-780652615_

### PR DESCRIPTION
**Pull request by djarecka**
closes #11

### CODE REVIEW

**Comment by effigies** [comment]
o_0

empty

**Comment by djarecka** [comment]
weird...

**Comment by djarecka** [comment]
https://github.com/djarecka/pydra-tutorial/blob/nested_fig/figures/nested_workflow.png

**Comment by djarecka** [comment]
not sure why it's shown to be empty, i can see the file on my branch

**Pull request merged**
