### PR TITLE
add type-checking to the second notebook

### PR DESCRIPTION
**Pull request by yibeichan**
Hi, I added the type-checking to the second notebook & updated the conda env yml file with pydra==0.23.0a0 so that type-checking can work.
Let me know if anything else needs to be added.

### CODE REVIEW

**Comment by yibeichan** [comment]
I know.. the run has failed because I intentionally set something wrong...
```
# This usage is incorrect according to static type hints:
task1b = add(a="hello", b="world")
task1b()
```

**Comment by effigies** [comment]
You can mark cells as expected exception raising so they don't fail.

**Comment by yibeichan** [comment]
thank you @effigies ! adding `:tags: [raises-exception]` fixed the problem. now we have errors from the notebook `7_twolevel_glm_nilearn`, I guess it's because we installed the latest pydra, and some of my old code is raising errors...

**Comment by yibeichan** [comment]
okay, one error from the second-level glm hasn't been fixed yet; we should expect all other notebooks to be error-free at this moment

**Comment by djarecka** [comment]
ok, thank you, I will just merge it now, so we can work on other things and come back to this issue later

**Pull request merged**
